"""update job application and interview tables

Revision ID: 38d30a863caf
Revises: bf3433160f83
Create Date: 2024-12-31 02:23:04.488076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d30a863caf'
down_revision: Union[str, None] = 'bf3433160f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('application_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'interviews', 'job_applications', ['application_id'], ['application_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'application_id')
    # ### end Alembic commands ###
