"""Add relationships to user and job models

Revision ID: 50589c06af46
Revises: 569dea43c3df
Create Date: 2024-12-21 00:36:32.110007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50589c06af46'
down_revision: Union[str, None] = '569dea43c3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('job_applications', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_job_application_user', 'job_applications', 'users', ['candidate_id'], ['id'])
    
    # op.add_column('job_applications', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_job_application_job', 'job_applications', 'jobs', ['job_id'], ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
