"""added violation

Revision ID: 51e4b54ffba7
Revises: 9ee8c435ee2d
Create Date: 2025-05-16 06:33:14.564791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e4b54ffba7'
down_revision: Union[str, None] = '9ee8c435ee2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('tab_switch_count', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('face_violation_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'face_violation_count')
    op.drop_column('interviews', 'tab_switch_count')
    # ### end Alembic commands ###
