"""Add relationship between User and Resume

Revision ID: 63b0e37020c6
Revises: d441fcbd7c40
Create Date: 2024-12-11 13:08:24.474557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b0e37020c6'
down_revision: Union[str, None] = 'd441fcbd7c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'user_id')
    # ### end Alembic commands ###
