"""Add INTERVIEW_COMPLETED status to ApplicationStatus enum

Revision ID: 92722301a473
Revises: d73f4f39a1f6
Create Date: 2025-05-16 02:54:49.384689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92722301a473'
down_revision: Union[str, None] = 'd73f4f39a1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'INTERVIEW COMPLETED' AFTER 'INTERVIEW_SCHEDULED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL doesn't allow removing enum values directly, so we need to recreate the enum
    
    # Create a new enum type without the 'INTERVIEW COMPLETED' value
    op.execute("CREATE TYPE applicationstatus_new AS ENUM ('APPLIED', 'SHORTLISTED', 'REJECTED', 'INTERVIEW_SCHEDULED')")
    
    # Find the table and column using this enum type
    # This query assumes your schema is public and the column is named status
    op.execute("""
        DO $$
        DECLARE
            table_name text;
            column_name text;
        BEGIN
            SELECT c.table_name, c.column_name
            INTO table_name, column_name
            FROM information_schema.columns c
            JOIN pg_type t ON t.typname = 'applicationstatus'
            JOIN pg_namespace n ON t.typnamespace = n.oid AND n.nspname = current_schema()
            WHERE c.data_type = 'USER-DEFINED' 
            AND c.udt_name = 'applicationstatus'
            LIMIT 1;
            
            -- Create a new column with new type
            EXECUTE 'ALTER TABLE ' || table_name || ' ADD COLUMN status_new applicationstatus_new';
            
            -- Convert data (with fallback for removed enum value)
            EXECUTE 'UPDATE ' || table_name || ' SET status_new = 
                CASE 
                    WHEN status::text = ''INTERVIEW COMPLETED'' THEN ''INTERVIEW_SCHEDULED''::applicationstatus_new
                    ELSE status::text::applicationstatus_new
                END';
                
            -- Drop old column and rename new one
            EXECUTE 'ALTER TABLE ' || table_name || ' DROP COLUMN status';
            EXECUTE 'ALTER TABLE ' || table_name || ' RENAME COLUMN status_new TO status';
        END $$;
    """)
    
    # Drop the old enum type
    op.execute("DROP TYPE applicationstatus")
    
    # Rename the new type to the original name
    op.execute("ALTER TYPE applicationstatus_new RENAME TO applicationstatus")
    # ### end Alembic commands ###
