"""Add INTERVIEW_COMPLETED statu s to ApplicationStatus enum

Revision ID: 9ee8c435ee2d
Revises: d081a15c0efa
Create Date: 2025-05-16 03:20:44.963650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee8c435ee2d'
down_revision: Union[str, None] = 'd081a15c0efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'INTERVIEW_COMPLETED' AFTER 'INTERVIEW_SCHEDULED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
