"""added mix max salaray in job

Revision ID: b5f51ea66a9a
Revises: 38d30a863caf
Create Date: 2025-01-07 22:50:15.055080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f51ea66a9a'
down_revision: Union[str, None] = '38d30a863caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('max_salary', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('min_salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'min_salary')
    op.drop_column('jobs', 'max_salary')
    # ### end Alembic commands ###
