"""Add sentiment_analysis and technical_knowledge to InterviewEvaluation

Revision ID: d73f4f39a1f6
Revises: d93d328debbb
Create Date: 2025-05-14 02:19:26.981344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73f4f39a1f6'
down_revision: Union[str, None] = 'd93d328debbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_evaluations', sa.Column('sentiment_analysis', sa.JSON(), nullable=True))
    op.add_column('interview_evaluations', sa.Column('technical_knowledge', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_evaluations', 'technical_knowledge')
    op.drop_column('interview_evaluations', 'sentiment_analysis')
    # ### end Alembic commands ###
