"""Add feedback_for_candidate to InterviewEvaluation

Revision ID: d93d328debbb
Revises: ec732ef693e7
Create Date: 2025-03-07 03:12:59.670931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93d328debbb'
down_revision: Union[str, None] = 'ec732ef693e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_evaluations', sa.Column('feedback_for_candidate', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_evaluations', 'feedback_for_candidate')
    # ### end Alembic commands ###
