"""Add InterviewEvaluation model and relationship

Revision ID: ec732ef693e7
Revises: b5f51ea66a9a
Create Date: 2025-03-07 02:11:33.789859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec732ef693e7'
down_revision: Union[str, None] = 'b5f51ea66a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_evaluations',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_score', sa.Float(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_index(op.f('ix_interview_evaluations_evaluation_id'), 'interview_evaluations', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_evaluations_evaluation_id'), table_name='interview_evaluations')
    op.drop_table('interview_evaluations')
    # ### end Alembic commands ###
